/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminEstoqueRouteImport } from './routes/admin/estoque'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminVendasRouteImport } from './routes/admin/vendas'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo/index'
import { Route as CatalogoProdutoIdRouteImport } from './routes/catalogo/produto.$id'
import { Route as ApiPublicFotoSplatRouteImport } from './routes/api/public/foto.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoProdutoIdRoute = CatalogoProdutoIdRouteImport.update({
  id: '/catalogo/produto/$id',
  path: '/catalogo/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFotoSplatRoute = ApiPublicFotoSplatRouteImport.update({
  id: '/api/public/foto/$',
  path: '/api/public/foto/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/catalogo/produto/$id': typeof CatalogoProdutoIdRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin': typeof AdminIndexRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/catalogo/produto/$id': typeof CatalogoProdutoIdRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/catalogo/produto/$id': typeof CatalogoProdutoIdRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entrar'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/vendas'
    | '/admin/'
    | '/catalogo/'
    | '/catalogo/produto/$id'
    | '/api/public/foto/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/vendas'
    | '/admin'
    | '/catalogo'
    | '/catalogo/produto/$id'
    | '/api/public/foto/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entrar'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/vendas'
    | '/admin/'
    | '/catalogo/'
    | '/catalogo/produto/$id'
    | '/api/public/foto/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  CatalogoProdutoIdRoute: typeof CatalogoProdutoIdRoute
  ApiPublicFotoSplatRoute: typeof ApiPublicFotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/produto/$id': {
      id: '/catalogo/produto/$id'
      path: '/catalogo/produto/$id'
      fullPath: '/catalogo/produto/$id'
      preLoaderRoute: typeof CatalogoProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/foto/$': {
      id: '/api/public/foto/$'
      path: '/api/public/foto/$'
      fullPath: '/api/public/foto/$'
      preLoaderRoute: typeof ApiPublicFotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminVendasRoute: typeof AdminVendasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminVendasRoute: AdminVendasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  CatalogoProdutoIdRoute: CatalogoProdutoIdRoute,
  ApiPublicFotoSplatRoute: ApiPublicFotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
