ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS images text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS show_in_catalog boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS featured boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_new boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.catalog_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_name text NOT NULL,
  phone text NOT NULL,
  fulfillment text NOT NULL DEFAULT 'retirada',
  address text,
  payment_method text NOT NULL DEFAULT 'pix',
  installments integer NOT NULL DEFAULT 1,
  notes text,
  total numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'aguardando',
  sale_id uuid REFERENCES public.sales(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.catalog_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.catalog_orders(id) ON DELETE CASCADE,
  variant_id uuid REFERENCES public.variants(id) ON DELETE SET NULL,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  size text NOT NULL DEFAULT 'Único',
  color text NOT NULL DEFAULT 'Único',
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_settings (
  id integer PRIMARY KEY DEFAULT 1,
  whatsapp_number text NOT NULL DEFAULT '5581999045295',
  order_intro text NOT NULL DEFAULT 'Olá! Quero fazer um pedido na Metah Veste:',
  banner_url text,
  logo_url text,
  banner_title text NOT NULL DEFAULT 'Metah Veste',
  banner_subtitle text NOT NULL DEFAULT 'Moda jovem, minimalista e cheia de atitude.',
  payment_options text[] NOT NULL DEFAULT ARRAY['pix','dinheiro','debito','credito','link'],
  fulfillment_options text[] NOT NULL DEFAULT ARRAY['retirada','entrega'],
  delivery_text text NOT NULL DEFAULT 'Entregamos na região. Combine o frete pelo WhatsApp.',
  show_out_of_stock boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT app_settings_single_row CHECK (id = 1)
);

INSERT INTO public.app_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_catalog_order_items_order ON public.catalog_order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_catalog_orders_created ON public.catalog_orders(created_at DESC);

CREATE TRIGGER catalog_orders_updated_at BEFORE UPDATE ON public.catalog_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER app_settings_updated_at BEFORE UPDATE ON public.app_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.catalog_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.catalog_orders TO service_role;
GRANT ALL ON public.catalog_order_items TO service_role;
GRANT ALL ON public.app_settings TO service_role;

-- All access now goes through the server (service role). No direct public access.
REVOKE ALL ON public.products FROM anon, authenticated;
REVOKE ALL ON public.variants FROM anon, authenticated;
REVOKE ALL ON public.customers FROM anon, authenticated;
REVOKE ALL ON public.sales FROM anon, authenticated;
REVOKE ALL ON public.sale_items FROM anon, authenticated;
REVOKE ALL ON public.stock_movements FROM anon, authenticated;
REVOKE ALL ON public.exchanges FROM anon, authenticated;

DROP POLICY IF EXISTS "open access products" ON public.products;
DROP POLICY IF EXISTS "open access variants" ON public.variants;
DROP POLICY IF EXISTS "open access customers" ON public.customers;
DROP POLICY IF EXISTS "open access sales" ON public.sales;
DROP POLICY IF EXISTS "open access sale_items" ON public.sale_items;
DROP POLICY IF EXISTS "open access stock_movements" ON public.stock_movements;
DROP POLICY IF EXISTS "open access exchanges" ON public.exchanges;

GRANT ALL ON public.products TO service_role;
GRANT ALL ON public.variants TO service_role;
GRANT ALL ON public.customers TO service_role;
GRANT ALL ON public.sales TO service_role;
GRANT ALL ON public.sale_items TO service_role;
GRANT ALL ON public.stock_movements TO service_role;
GRANT ALL ON public.exchanges TO service_role;